name: the-ring-effect
recipe: pantheon
config:
  framework: drupal8
  env: dev
  site: the-ring-effect
  id: 52d99f65-f27e-4152-9ca3-e5180d9c5447
events:
  post-db-import:
    - appserver: cd $LANDO_MOUNT && composer install
services:
  appserver:
    overrides:
      services:
        environment:
          BEHAT_PARAMS: >-
            {"extensions" : {"Behat\\MinkExtension" : {"base_url" :
            "http://nginx/"}, "Drupal\\DrupalExtension" : {"drush" :   {
            "root":  "/app/web" }}}}
tooling:
  phplint:
    service: appserver
    cmd: /app/vendor/bin/phplint
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat
