name: poderopedia
recipe: pantheon
config:
  framework: drupal8
  env: dev
  site: poderopedia
  id: d4e94e30-69fe-42d4-8b6b-a983f3cd50b4
events:
  post-db-import:
    - appserver: cd $LANDO_MOUNT && composer install
services:
  appserver:
    overrides:
      environment:
        BEHAT_PARAMS: >-
          {"extensions" : {"Behat\\MinkExtension" : {"base_url" :
          "http://nginx/"}, "Drupal\\DrupalExtension" : {"drush" :   {
          "root":  "/app/web" }}}}
tooling:
  phplint:
    service: appserver
    cmd: /app/vendor/bin/phplint
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat
